name: Build Typst document
on:
  push:
    paths:
      - "*.typ"
      - src/**
      - .github/workflows/build.yml
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: fontist/setup-fontist@v2
        with:
          fontist-version: "1.21.1"
          cache-dependency-path: manifest.yml
      - run: fontist manifest-install manifest.yml
      - uses: typst-community/setup-typst@v3
        id: setup-typst
      - name: Build PDF
        run: typst compile main.typ main.pdf --font-path ~/.fontist/fonts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-pdf
          path: "*.pdf"

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: template-pdf
      - uses: softprops/action-gh-release@v2
        with:
          files: "*.pdf"
